// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetworkWebChess.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NetworkWebChess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NetworkWebChess.Data.Entities.GameEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("BlackKingMoved")
                        .HasColumnType("boolean");

                    b.Property<bool>("BlackKingsideRookMoved")
                        .HasColumnType("boolean");

                    b.Property<string>("BlackPlayerId")
                        .HasColumnType("text");

                    b.Property<bool>("BlackQueensideRookMoved")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentFen")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentPlayer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EnPassantTarget")
                        .HasColumnType("text");

                    b.Property<string>("GameResult")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastActivityUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WhiteKingMoved")
                        .HasColumnType("boolean");

                    b.Property<bool>("WhiteKingsideRookMoved")
                        .HasColumnType("boolean");

                    b.Property<string>("WhitePlayerId")
                        .HasColumnType("text");

                    b.Property<bool>("WhiteQueensideRookMoved")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
